// +build !windows
package zebrazxp13

func ZBRCloseHandle(handle Handle) (ret uintptr, err uint) { panic("ZBRCloseHandle cannot be called on a non-Windows platform"); return 0,0 }
func ZBRGetHandle(drvName string) (ret uint, handle Handle, prn_type uint, err uint) { panic("ZBRGetHandle cannot be called on a non-Windows platform"); return 0,0,0,0 }
func ZBRPRNCheckForErrors() (ret uintptr) { panic("ZBRPRNCheckForErrors cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNChkDueForCleaning() (ret uintptr) { panic("ZBRPRNChkDueForCleaning cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNClrColorImgBuf() (ret uintptr) { panic("ZBRPRNClrColorImgBuf cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNClrColorImgBufs() (ret uintptr) { panic("ZBRPRNClrColorImgBufs cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNClrErrStatusLn() (ret uintptr) { panic("ZBRPRNClrErrStatusLn cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNClrMediaPath() (ret uintptr) { panic("ZBRPRNClrMediaPath cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNClrMonoImgBuf() (ret uintptr) { panic("ZBRPRNClrMonoImgBuf cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNClrMonoImgBufs() (ret uintptr) { panic("ZBRPRNClrMonoImgBufs cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNClrSpecifiedBmp() (ret uintptr) { panic("ZBRPRNClrSpecifiedBmp cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNEjectCard(handle Handle, prn_type uint) (ret uintptr, err uint) { panic("ZBRPRNEjectCard cannot be called on a non-Windows platform"); return 0,0 }
func ZBRPRNEnableMagReadDataEncryption() (ret uintptr) { panic("ZBRPRNEnableMagReadDataEncryption cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNEndSmartCard() (ret uintptr) { panic("ZBRPRNEndSmartCard cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNFlipCard() (ret uintptr) { panic("ZBRPRNFlipCard cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetChecksum() (ret uintptr) { panic("ZBRPRNGetChecksum cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetCleaningParam() (ret uintptr) { panic("ZBRPRNGetCleaningParam cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetIPAddress() (ret uintptr) { panic("ZBRPRNGetIPAddress cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetMsgSuppressionState() (ret uintptr) { panic("ZBRPRNGetMsgSuppressionState cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetOpParam() (ret uintptr) { panic("ZBRPRNGetOpParam cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetPanelsPrinted() (ret uintptr) { panic("ZBRPRNGetPanelsPrinted cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetPanelsRemaining() (ret uintptr) { panic("ZBRPRNGetPanelsRemaining cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetPrintCount() (ret uintptr) { panic("ZBRPRNGetPrintCount cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetPrinterOptions() (ret uintptr) { panic("ZBRPRNGetPrinterOptions cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetPrinterSerialNumb() (ret uintptr) { panic("ZBRPRNGetPrinterSerialNumb cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetPrinterSerialNumber() (ret uintptr) { panic("ZBRPRNGetPrinterSerialNumber cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetPrinterStatus() (ret uintptr) { panic("ZBRPRNGetPrinterStatus cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetPrintHeadSerialNumb() (ret uintptr) { panic("ZBRPRNGetPrintHeadSerialNumb cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetPrintHeadSerialNumber() (ret uintptr) { panic("ZBRPRNGetPrintHeadSerialNumber cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetPrintStatus() (ret uintptr) { panic("ZBRPRNGetPrintStatus cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetSDKProductVer() (ret uintptr) { panic("ZBRPRNGetSDKProductVer cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetSDKVer() (major, minor, engLevel int) { panic("ZBRPRNGetSDKVer cannot be called on a non-Windows platform"); return 0,0,0 }
func ZBRPRNGetSDKVsn() (ret uintptr) { panic("ZBRPRNGetSDKVsn cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNGetSensorStatus() (ret uintptr) { panic("ZBRPRNGetSensorStatus cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNImmediateParamSave() (ret uintptr) { panic("ZBRPRNImmediateParamSave cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNIsPrinterReady() (ret uintptr) { panic("ZBRPRNIsPrinterReady cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNMoveCard() (ret uintptr) { panic("ZBRPRNMoveCard cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNMoveCardBkwd() (ret uintptr) { panic("ZBRPRNMoveCardBkwd cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNMoveCardFwd() (ret uintptr) { panic("ZBRPRNMoveCardFwd cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNMovePrintReady() (ret uintptr) { panic("ZBRPRNMovePrintReady cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNPrintCardPanel() (ret uintptr) { panic("ZBRPRNPrintCardPanel cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNPrintClearVarnish() (ret uintptr) { panic("ZBRPRNPrintClearVarnish cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNPrintColorImgBuf() (ret uintptr) { panic("ZBRPRNPrintColorImgBuf cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNPrintHologramOverlay() (ret uintptr) { panic("ZBRPRNPrintHologramOverlay cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNPrintMonoImgBuf() (ret uintptr) { panic("ZBRPRNPrintMonoImgBuf cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNPrintMonoImgBufEx() (ret uintptr) { panic("ZBRPRNPrintMonoImgBufEx cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNPrintMonoPanel() (ret uintptr) { panic("ZBRPRNPrintMonoPanel cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNPrintPrnFile() (ret uintptr) { panic("ZBRPRNPrintPrnFile cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNPrintTestCard() (ret uintptr) { panic("ZBRPRNPrintTestCard cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNPrintVarnish() (ret uintptr) { panic("ZBRPRNPrintVarnish cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNPrintVarnishEx() (ret uintptr) { panic("ZBRPRNPrintVarnishEx cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNReadMag() (ret uintptr) { panic("ZBRPRNReadMag cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNReadMagByTrk() (ret uintptr) { panic("ZBRPRNReadMagByTrk cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNResetMagEncoder() (ret uintptr) { panic("ZBRPRNResetMagEncoder cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNResetPrinter() (ret uintptr) { panic("ZBRPRNResetPrinter cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNResync() (ret uintptr) { panic("ZBRPRNResync cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNReversePrintReady() (ret uintptr) { panic("ZBRPRNReversePrintReady cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSelfAdj() (ret uintptr) { panic("ZBRPRNSelfAdj cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetCardFeedingMode() (ret uintptr) { panic("ZBRPRNSetCardFeedingMode cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetCleaningParam() (ret uintptr) { panic("ZBRPRNSetCleaningParam cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetColorContrast() (ret uintptr) { panic("ZBRPRNSetColorContrast cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetContrastIntensityLvl() (ret uintptr) { panic("ZBRPRNSetContrastIntensityLvl cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetEncoderCoercivity() (ret uintptr) { panic("ZBRPRNSetEncoderCoercivity cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetEncodingDir() (ret uintptr) { panic("ZBRPRNSetEncodingDir cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetEndOfPrint() (ret uintptr) { panic("ZBRPRNSetEndOfPrint cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetHologramIntensity() (ret uintptr) { panic("ZBRPRNSetHologramIntensity cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetMagEncodingStd() (ret uintptr) { panic("ZBRPRNSetMagEncodingStd cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetMonoContrast() (ret uintptr) { panic("ZBRPRNSetMonoContrast cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetMonoIntensity() (ret uintptr) { panic("ZBRPRNSetMonoIntensity cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetOverlayMode() (ret uintptr) { panic("ZBRPRNSetOverlayMode cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetPrintHeadResistance() (ret uintptr) { panic("ZBRPRNSetPrintHeadResistance cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetRelativeXOffset() (ret uintptr) { panic("ZBRPRNSetRelativeXOffset cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetRelativeYOffset() (ret uintptr) { panic("ZBRPRNSetRelativeYOffset cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetStartPrintSideBOffset() (ret uintptr) { panic("ZBRPRNSetStartPrintSideBOffset cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetStartPrintSideBXOffset() (ret uintptr) { panic("ZBRPRNSetStartPrintSideBXOffset cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetStartPrintSideBYOffset() (ret uintptr) { panic("ZBRPRNSetStartPrintSideBYOffset cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetStartPrintXOffset() (ret uintptr) { panic("ZBRPRNSetStartPrintXOffset cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetStartPrintYOffset() (ret uintptr) { panic("ZBRPRNSetStartPrintYOffset cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSetTrkDensity() (ret uintptr) { panic("ZBRPRNSetTrkDensity cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNStartCleaningCardSeq() (ret uintptr) { panic("ZBRPRNStartCleaningCardSeq cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNStartCleaningSeq() (ret uintptr) { panic("ZBRPRNStartCleaningSeq cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNStartSmartCard() (ret uintptr) { panic("ZBRPRNStartSmartCard cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNSuppressStatusMsgs() (ret uintptr) { panic("ZBRPRNSuppressStatusMsgs cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNUpgradeFirmware() (ret uintptr) { panic("ZBRPRNUpgradeFirmware cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNWriteBarCode() (ret uintptr) { panic("ZBRPRNWriteBarCode cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNWriteBox() (ret uintptr) { panic("ZBRPRNWriteBox cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNWriteBoxEx() (ret uintptr) { panic("ZBRPRNWriteBoxEx cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNWriteMag() (ret uintptr) { panic("ZBRPRNWriteMag cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNWriteMagByTrk() (ret uintptr) { panic("ZBRPRNWriteMagByTrk cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNWriteMagPassThru() (ret uintptr) { panic("ZBRPRNWriteMagPassThru cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNWriteText() (ret uintptr) { panic("ZBRPRNWriteText cannot be called on a non-Windows platform"); return 0 }
func ZBRPRNWriteTextEx() (ret uintptr) { panic("ZBRPRNWriteTextEx cannot be called on a non-Windows platform"); return 0 }
